[main]
font=JetBrainsMono Nerd Font:size=12
pad=12x12
shell=/bin/bash

[colors-dark]
alpha=0.95
background=111111
foreground=ffffff
cursor=ffffff ffffff

#[colors-dark]
#alpha=0.85          # Ajuste entre 0.0 (invisível) e 1.0 (sólido)
#background=000000   # Fundo preto para o Pywal brilhar por cima
#foreground=ffffff


[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

[url]
launch=qutebrowser ${url}

[cursor]
style=block
blink=yes
